In [1]:
import numpy as np

## Ans for Q1

In [2]:
def compute_vander_matrix(vector, N=None, increasing=False):
    """
    compute the Alexandre-Theophile Vandermonde matrix of a vector.
    The order of the powers is determined by the increasing boolean argument. Specifically, when
    increasing is False, the i-th output column is the input vector raised element-wise to the power
    of N - i - 1.
    :param vector:1-D input array
    :param N: int, optional, Number of columns in the output.
              If N is not specified, a square array is returned (N = len(x)).
    :param increasing: bool, optional
                       Order of the powers of the columns. If True, the powers
                       increase from left to right, if False (the default) they are reversed.
    """
    max_order = N if N else vector.shape[0]
    vec = vector.reshape(-1, 1)
    if increasing:
        order_of_power = range(max_order)
    else:
        order_of_power = range(max_order-1, -1, -1)
    
    powers = [
        np.power(vec, ord_)
        for ord_ in order_of_power
    ]
    return np.hstack(powers)

In [3]:
inp = np.array([3, 6, 7, 8])
print(compute_vander_matrix(inp))

[[ 27   9   3   1]
 [216  36   6   1]
 [343  49   7   1]
 [512  64   8   1]]


## Ans for Q2

In [4]:
def find_moving_avg(seq, window_size):
    """
    Find moving average in an array over a window:
    """
    avgs = []
    no_of_possible_mv_avg = seq.shape[0] - window_size + 1
    for i in range(no_of_possible_mv_avg):
        avgs.append(np.average(seq[i: i+ window_size]))
    return avgs

inp = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
find_moving_avg(inp, 3)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]